name: Build Backend Image

on:
  pull_request:
    types:
      - opened
    paths:
      - backend/**
  push:
    branches:
      - master
    paths:
      - backend/**

jobs:
  build:
    env:
      BACKEND_IMAGE: deepfenceio/deepfence_saas_backend:${{ github.head_ref }}-${{ github.sha }}
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set tag for master
        if: github.event_name == 'push'
        run: |
          echo "BACKEND_IMAGE=deepfenceio/deepfence_saas_backend:$GITHUB_REF_NAME-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Set tag for other braches
        if: github.event_name == 'pull_request'
        run: |
          echo "BACKEND_IMAGE=deepfenceio/deepfence_saas_backend:$GITHUB_HEAD_REF-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Test
        run: |
          echo $BACKEND_IMAGE